### ISSUE TITLE
建造者模式很好，但是我有些问题

### ISSUE THREAD

**Issue by mrchenmo** [NeglectedByBoss/Novate#1]
final Observable.Transformer schedulersTransformer = new Observable.Transformer() {       @Override        public Object call(Object observable) {            return ((Observable) observable).subscribeOn(Schedulers.io())                  .unsubscribeOn(Schedulers.io())                   .observeOn(AndroidSchedulers.mainThread());       }    };
这个转义器最好改下，我做了以下修改不知道对不对，请您看下

<T> Observable.Transformer<T, T> schedulersTransformer() {
        return new Observable.Transformer<T, T>() {
            @Override
            public Observable<T> call(Observable<T> observable) {
                return observable.subscribeOn(Schedulers.io())
                        .unsubscribeOn(Schedulers.io())
                        .observeOn(AndroidSchedulers.mainThread());
            }
        };
    }
这样更改以后再Observe的时候不会出现数据检查的lint警告

**Comment by NeglectedByBoss** [comment]
也可以的

**Comment by mrchenmo** [comment]
还有BaseApiservice这个类的@Post（{url}）和@Path的url实际上也是拼接不上的，我在项目上试了很多次。
  @POST("{path}")
    Observable<ResponseBody> executePost(
            @Path(value = "path", encoded = true) String path,
            @QueryMap Map<String, String> map
    );
后来经过学习更改成这样了，希望作者可以继续维护这个库。还有一个问题我不明白，建造者模式的Builder和build产生了许多无用的方法和变量，是不是可以优化下，我还没有彻底理解建造者模式所以没有去动代码。作者有没有联系方式啊，这个库还是很好的，我想好好优化下，自用

**Comment by NeglectedByBoss** [comment]
可以加我ＱＱ　１０５７５３１６６４

**Comment by NeglectedByBoss** [comment]
这里的ｕｒｌ值的全路径（ｈｏｓｔ＋ｐａｔｈ），　并不是只是ｐａｔｈ

**Comment by spmonk** [comment]
@NeglectedByBoss  hello,你的Novate是不是单例的，如果想切换baseurl,是不是需要重新实例化

**Comment by NeglectedByBoss** [comment]
是的
